// ===================================================
//  Star Wars: EaW - Localization Tool
//  Created by EMP_UA
// ============================================================
//  Model/TsvRow.cs
//  UA: Модель даних одного рядка TSV-таблиці.
//      Відповідає структурі, яку генерує інструмент-екстрактор.
//  EN: Data model for one TSV table row.
//      Matches the structure generated by the extractor tool.
// ============================================================

namespace EaWLocalizer.Model;

/// <summary>
/// UA: Один TSV-рядок = один перекладний елемент гри.
///
///     Заголовок таблиці:
///     FilePath | FileType | Key | OriginalText | TranslatedText | OriginalEncodingName
///
///     Приклад (DAT):
///     GameData\Text\MasterTextFile_en.dat | dat | 3A2F1B0C | Imperial Star Destroyer | | utf-16-le
///
///     Приклад (XML):
///     GameData\Units\Empire.xml | xml | /Units/Unit[1]/Name | Star Destroyer | | utf-8
///
///     Приклад (TXT):
///     GameData\AI\AiPlayers.txt | txt | 3 | Rebel Leader | | utf-8
///
/// EN: One TSV row = one translatable game element.
///
///     Table header:
///     FilePath | FileType | Key | OriginalText | TranslatedText | OriginalEncodingName
/// </summary>
public class TsvRow
{
    // UA: Відносний шлях до вихідного файлу гри (відносно OriginalDir).
    //     Пакувальник використовує для знаходження та перезапису файлу.
    // EN: Relative path to the source game file (relative to OriginalDir).
    //     The re-packer uses this to locate and overwrite the file.
    public string FilePath { get; set; } = "";

    // UA: Тип файлу: "dat" | "xml" | "txt".
    //     Пакувальник обирає стратегію запису залежно від типу.
    // EN: File type: "dat" | "xml" | "txt".
    //     The re-packer selects the write strategy based on the type.
    public string FileType { get; set; } = "";

    // UA: Технічний ключ запису. НЕ перекладається.
    //     DAT → CRC32 у hex; XML → XPath або порядковий індекс; TXT → номер рядка.
    //     Пакувальник використовує щоб знайти точну позицію у файлі.
    // EN: Technical record key. NOT translated.
    //     DAT → CRC32 hex; XML → XPath or ordinal index; TXT → line number.
    //     The re-packer uses this to find the exact position in the file.
    public string Key { get; set; } = "";

    // UA: Оригінальний текст (зазвичай англійська).
    //     Відправляється у Gemini API для перекладу.
    //     Може містити \n \t %s {0} [COLOR...] — зберігати при перекладі!
    // EN: Original text (usually English).
    //     Sent to the Gemini API for translation.
    //     May contain \n \t %s {0} [COLOR...] — preserve during translation!
    public string OriginalText { get; set; } = "";

    // UA: Перекладений текст. Порожній рядок означає «ще не перекладено».
    //     Після перекладу через API — тут зберігається Ukrainian text.
    // EN: Translated text. Empty string means "not yet translated".
    //     After API translation — stores the Ukrainian text.
    public string TranslatedText { get; set; } = "";

    // UA: Ім'я кодування вихідного файлу (utf-8, utf-16-le, windows-1252...).
    //     Пакувальник зобов'язаний записати файл у тому самому кодуванні.
    // EN: Source file encoding name (utf-8, utf-16-le, windows-1252...).
    //     The re-packer must write the file in the same encoding.
    public string OriginalEncodingName { get; set; } = "";

    // ── HELPERS ──────────────────────────────────────────────────────────

    /// <summary>
    /// UA: Чи потребує цей рядок перекладу через API?
    /// EN: Does this row still need API translation?
    /// </summary>
    public bool NeedsTranslation => string.IsNullOrWhiteSpace(TranslatedText);

    /// <summary>
    /// UA: Серіалізує рядок у формат TSV.
    ///     Символи реальної табуляції в тексті замінюються на "\\t"
    ///     (двосимвольна послідовність) — безпечно для TSV-парсера.
    ///     \n та інші плейсхолдери ігри вже є рядками, не символами,
    ///     тому їх екранування НЕ потрібне.
    /// EN: Serialises the row to TSV format.
    ///     Real tab characters in text are replaced with "\\t"
    ///     (two-character sequence) — safe for the TSV parser.
    ///     \n and other game placeholders are already strings, not characters,
    ///     so escaping them is NOT required.
    /// </summary>
    public string ToTsvLine() =>
        string.Join("\t",
            FilePath,
            FileType,
            Key,
            EscapeField(OriginalText),
            EscapeField(TranslatedText),
            OriginalEncodingName);

    // UA: Екранує лише реальний символ Tab (0x09) у значенні поля.
    // EN: Escapes only the real Tab character (0x09) in a field value.
    static string EscapeField(string s) => s?.Replace("\t", "\\t") ?? "";
}
